# Generated by Django 4.1.3 on 2022-11-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tagmodel_options_rename_tag_tagmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemodel',
            name='eng_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='titlemodel',
            name='other_name',
            field=models.TextField(default=''),
        ),
    ]
