# Generated by Django 4.1.3 on 2022-11-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_titlemodel_eng_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='content',
            field=models.TextField(),
        ),
    ]
