# Generated by Django 4.1.3 on 2022-11-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_chaptermodel_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaptermodel',
            old_name='number',
            new_name='count',
        ),
    ]
