# Generated by Django 4.1.3 on 2022-11-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_number_chaptermodel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chaptermodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
