# Generated by Django 4.1.3 on 2022-11-08 13:59

from django.db import migrations
from ..models import *

def add_test_objects(apps, scheme_editor):
    TagModel.objects.create(
        name = 'Мечта'
    )

    TagModel.objects.create(
        name = 'Мечты'
    )

    TagModel.objects.create(
        name = 'Любовь'
    )

    TitleModel.objects.create(
        rus_name = 'Книга о мечтах',
        eng_name = 'Book about dreams',
        other_name = '',
        desc = 'Марафон мечт'
    ).tags.set([TagModel.objects.get(name='Мечта'), TagModel.objects.get(name='Мечты')])

    TitleModel.objects.create(
        rus_name = 'Книга о любви',
        eng_name = 'Book about love',
        other_name = '',
        desc = 'Марафон любви'
    ).tags.set([TagModel.objects.get(name='Любовь')])

    VolumeModel.objects.create(
        title = TitleModel.objects.get(rus_name='Книга о мечтах'),
        name = "Все о мечтах",
        cost = 22500,
        number = 140
    )

    ChapterModel.objects.create(
        volume = VolumeModel.objects.get(title__rus_name='Книга о мечтах'),
        count = 20,
        content = 'gsgsdgsdgfsg'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_chaptermodel_likes_alter_chaptermodel_views'),
    ]

    operations = [
        migrations.RunPython(add_test_objects)
    ]
